name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Deploy to Server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.5
      with:
        username: ${{ secrets.SSH_USER }}
        server: ${{ secrets.SSH_SERVER }}
        port: 22
        local_path: './dist/*'
        remote_path: ${{ secrets.SSH_PATH }}
        sftp_only: true
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  flush-cdn:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: jwyxym/jwyxym/aliyun-esa-cache@master
        with:
          access_key_id: ${{ secrets.ESA_ID }}
          access_key_secret: ${{ secrets.ESA_KEY }}
          site_id: ${{ secrets.ESA_SITE_ID }}
          url_target: ${{ secrets.ESA_URL }}
          flush_type: "file"